-- remove all zeroes in salary and get avg
SELECT AVG(REPLACE(SALARY, '0', '')) AS MODIFIED_SALARY FROM WORKER;
-- we can also use CEIL to get next rounded number
SELECT CEIL(AVG(REPLACE(SALARY, '0', ''))) AS MODIFIED_SALARY FROM WORKER;
-- USING CASE
SELECT CASE
WHEN MONTHS >= 8 THEN 'GREATER THAN 8'
WHEN MONTHS >= 15 THEN 'GREATER THAN 15'
ELSE 'NO NEED'
END AS SOME_DESCRIPTION
FROM EMPLOYEE;
